### ISSUE TITLE
Idée Addon

### ISSUE THREAD

**Issue by BuursTV** [Citillara/NepNep#1]
Inclure les absorptions comme négatif

Absorption, healing,  et potions x 2 en malus, si je fais un heal ou une absorb de  500, je perds 1000 !
Doubler les dégats recus en score, exemple : si je prend un coup à 50, j'ai -100 de score.

Mourrir fait perdre un montant énorme de points ( a définir plus tard)

Enlever les pts bonus quand on tue un ennemi

100pts bonus par quête accompli

Soins alliés neutre = pas de pts bonus ou malus

Perte de points quand on saute ? (-50 pts)

**Comment by Citillara** [comment]
Implémenté
