### ISSUE TITLE
HOTFIX 2.0

### ISSUE THREAD

**Issue by BuursTV** [Citillara/NepNep#2]
Pouvoir ouvrir une session de challenge score en ajoutant un des participants ainsi voir leur score rapidement (entre concurrents) avec un classement mise a jour en direct, ainsi voir l'évolution de chaque score de chacun pour chaque participant (d'un même serveur)

Fenêtre score plus grosse

Si on groupe -1.000.000 de pts

**Comment by Citillara** [comment]
Pas de système de session : trop compliqué

**Comment by Citillara** [comment]
La fenetre de score est définie par une police de taille fixe dans le jeu :/
